import '../../discovery_planning/models/heritage_place.dart';

/// The supplied 17-place content, adapted to the existing catalog schema.
/// Existing seed IDs are retained to protect saved references.
abstract final class PredefinedPlaces {
  static const aliases = <String, String>{
    "sigiriya": "sigiriya-rock-fortress",
    "galle-fort": "galle-fort-and-old-town",
    "dambulla": "cave-temples-dambulla",
    "nine-arch": "nine-arch-bridge-ella",
    "tooth-temple": "temple-of-the-tooth-kandy",
  };
  static const places = <HeritagePlace>[
    HeritagePlace(
      id: "sigiriya",
      category: "Forts",
      name: "Sigiriya Rock Fortress",
      imagePath: "assets/places/sigiriya_rock_fortress.jpg",
      shortDescription: "Ancient rock fortress, royal citadel and landscaped garden complex in Sri Lanka's Cultural Triangle.",
      description: "Sigiriya is one of Sri Lanka's most important archaeological sites. The ancient citadel is centred on a massive rock rising above the surrounding landscape. It is associated especially with King Kashyapa and is known for its palace ruins, defensive structures, water gardens, frescoes, Mirror Wall and the monumental lion gateway that gave the site its name.",
      city: "Sigiriya",
      district: "Matale",
      address: "Sigiriya, Matale District, Central Province, Sri Lanka",
      historicalPeriod: "Ancient Sri Lanka; strongly associated with the reign of King Kashyapa, 5th century CE",
      openingHours:
          "Check current official visitor information before visiting",
      entranceFee: "Check current official ticket information before visiting",
      accessibilityInfo: "The visit involves substantial walking, stairs and a steep climb to the summit. Some areas may be difficult for visitors with limited mobility.",
      latitude: 7.9570,
      longitude: 80.7603,
      rating: 0,
      reviewCount: 0,
      isActive: true,
      isFeatured: true,
      highlights: [
        "Sigiriya Rock",
        "Lion gateway",
        "Ancient frescoes",
        "Mirror Wall",
        "Water gardens",
        "Summit palace ruins",
        "Archaeological landscape",
      ],
    ),
    HeritagePlace(
      id: "quadrangle-polonnaruwa",
      category: "Ancient Cities",
      name: "Quadrangle (Polonnaruwa)",
      imagePath: "assets/places/quadrangle_polonnaruwa.jpg",
      shortDescription: "A concentrated group of important religious and architectural monuments within the ancient city of Polonnaruwa.",
      description: "The Quadrangle is one of the most remarkable archaeological areas in Polonnaruwa. Within a compact raised precinct are several important structures connected with the medieval capital, including the Vatadage, Hatadage, Atadage and other stone monuments. The area demonstrates the craftsmanship, religious traditions and architecture of the Polonnaruwa period.",
      city: "Polonnaruwa",
      district: "Polonnaruwa",
      address: "Ancient City of Polonnaruwa, Polonnaruwa, Sri Lanka",
      historicalPeriod: "Polonnaruwa Kingdom; mainly 11th–13th centuries CE",
      openingHours:
          "Check current official archaeological-site visitor information",
      entranceFee: "Check current official Polonnaruwa ticket information",
      accessibilityInfo: "The archaeological area involves outdoor walking over uneven historic surfaces. Accessibility varies between individual monuments.",
      latitude: 7.9467,
      longitude: 81.0014,
      rating: 0,
      reviewCount: 0,
      isActive: true,
      isFeatured: false,
      highlights: [
        "Polonnaruwa Vatadage",
        "Hatadage",
        "Atadage",
        "Stone carvings",
        "Ancient religious architecture",
        "Archaeological ruins",
      ],
    ),
    HeritagePlace(
      id: "galle-fort",
      category: "Forts",
      name: "Galle Fort and Old Town",
      imagePath: "assets/places/galle_fort_and_old_town.jpg",
      shortDescription: "Historic fortified coastal city combining European colonial architecture with South Asian traditions.",
      description: "Galle Fort is a historic fortified town on Sri Lanka's southwestern coast. Portuguese fortifications were later extensively developed by the Dutch, with further changes during British rule. The fort remains a living urban area containing ramparts, bastions, streets, religious buildings, museums and colonial-era architecture.",
      city: "Galle",
      district: "Galle",
      address: "Galle Fort, Galle, Southern Province, Sri Lanka",
      historicalPeriod: "Portuguese, Dutch and British colonial periods; from the 16th century",
      openingHours: "The fort is a living urban area; individual attractions may have their own opening hours",
      entranceFee: "General access to the fort area is free; individual attractions may charge admission",
      accessibilityInfo: "Many streets and public areas can be explored on foot, but historic ramparts, steps and uneven surfaces may limit accessibility in some areas.",
      latitude: 6.0260,
      longitude: 80.2170,
      rating: 0,
      reviewCount: 0,
      isActive: true,
      isFeatured: true,
      highlights: [
        "Fort ramparts",
        "Galle Lighthouse",
        "Clock Tower",
        "Dutch Reformed Church",
        "Historic streets",
        "Colonial architecture",
        "Ocean views",
      ],
    ),
    HeritagePlace(
      id: "adams-peak",
      category: "Temples",
      name: "Adam's Peak",
      imagePath: "assets/places/adams_peak.jpg",
      shortDescription: "Sacred mountain and major pilgrimage destination known for its summit footprint shrine and sunrise views.",
      description: "Adam's Peak, also known as Sri Pada, is one of Sri Lanka's most significant pilgrimage mountains. The summit is associated with religious traditions followed by several faiths. Pilgrims traditionally climb the mountain using a long stairway, often at night, to reach the summit around sunrise.",
      city: "Nallathanniya / Sri Pada area",
      district: "Ratnapura",
      address: "Sri Pada / Adam's Peak, Sri Lanka",
      historicalPeriod:
          "Ancient pilgrimage tradition continuing through the present day",
      openingHours: "Access and pilgrimage conditions vary by season; check current local conditions before climbing",
      entranceFee: "Check current local visitor information",
      accessibilityInfo: "The climb is physically demanding and includes thousands of steps. It is not suitable for many visitors with significant mobility limitations.",
      latitude: 6.8096,
      longitude: 80.4994,
      rating: 0,
      reviewCount: 0,
      isActive: true,
      isFeatured: false,
      highlights: [
        "Sacred footprint shrine",
        "Pilgrimage route",
        "Mountain scenery",
        "Sunrise",
        "Summit views",
      ],
    ),
    HeritagePlace(
      id: "dambulla",
      category: "Temples",
      name: "Cave Temples (Dambulla)",
      imagePath: "assets/places/cave_temples_dambulla.jpg",
      shortDescription: "Historic Buddhist cave-temple complex containing statues and extensive religious wall paintings.",
      description: "The Dambulla cave-temple complex is one of Sri Lanka's best-known Buddhist heritage sites. A series of caves contain numerous Buddha images, statues and extensive paintings created and restored over many centuries. The elevated temple complex also provides views over the surrounding landscape.",
      city: "Dambulla",
      district: "Matale",
      address: "Dambulla Cave Temple, Dambulla, Central Province, Sri Lanka",
      historicalPeriod: "Ancient origins with additions and restoration across many centuries",
      openingHours:
          "Check current official visitor information before visiting",
      entranceFee: "Check current official ticket information before visiting",
      accessibilityInfo: "Reaching the caves requires an uphill walk and stairs. Appropriate temple dress and footwear procedures should be respected.",
      latitude: 7.8567,
      longitude: 80.6492,
      rating: 0,
      reviewCount: 0,
      isActive: true,
      isFeatured: true,
      highlights: [
        "Cave shrines",
        "Buddha statues",
        "Ancient murals",
        "Religious art",
        "Rock temple",
        "Panoramic views",
      ],
    ),
    HeritagePlace(
      id: "abhayagiri-dagoba-anuradhapura",
      category: "Temples",
      name: "Abhayagiri Dagoba",
      imagePath: "assets/places/abhayagiri_dagoba_anuradhapura.jpg",
      shortDescription: "Monumental ancient stupa within the historic Abhayagiri monastic complex at Anuradhapura.",
      description: "Abhayagiri was one of the great Buddhist monastic centres of ancient Anuradhapura. Its monumental stupa dominates the archaeological landscape and reflects the scale and importance of the monastery that developed around it. The wider complex contains archaeological remains connected with monastic life, religious practice and ancient Sri Lankan architecture.",
      city: "Anuradhapura",
      district: "Anuradhapura",
      address: "Abhayagiri Monastery Complex, Anuradhapura, Sri Lanka",
      historicalPeriod: "Ancient Anuradhapura period",
      openingHours:
          "Check current Anuradhapura archaeological-site visitor information",
      entranceFee:
          "Check current official archaeological-site ticket information",
      accessibilityInfo: "The wider archaeological zone requires walking between monuments. Ground conditions and accessibility vary.",
      latitude: 8.3712,
      longitude: 80.3955,
      rating: 0,
      reviewCount: 0,
      isActive: true,
      isFeatured: false,
      highlights: [
        "Abhayagiri Stupa",
        "Ancient monastery",
        "Stone carvings",
        "Archaeological ruins",
        "Buddhist heritage",
      ],
    ),
    HeritagePlace(
      id: "nine-arch",
      category: "Architecture",
      name: "Nine Arch Bridge",
      imagePath: "assets/places/nine_arch_bridge_ella.jpg",
      shortDescription: "Iconic railway viaduct surrounded by the green hill-country landscape near Ella.",
      description: "The Nine Arch Bridge is one of Sri Lanka's best-known railway landmarks. The curved stone-and-brick viaduct crosses a lush valley between Ella and Demodara and is especially popular for photography when trains cross the bridge.",
      city: "Ella",
      district: "Badulla",
      address: "Nine Arch Bridge, Ella / Demodara, Badulla District, Sri Lanka",
      historicalPeriod: "British colonial railway era; early 20th century",
      openingHours: "Outdoor site; visit during safe daylight conditions and follow railway safety guidance",
      entranceFee:
          "General viewpoint access may be free; check local access conditions",
      accessibilityInfo: "Common approaches involve walking on uneven paths and slopes. Visitors must remain cautious around the active railway.",
      latitude: 6.8768,
      longitude: 81.0608,
      rating: 0,
      reviewCount: 0,
      isActive: true,
      isFeatured: true,
      highlights: [
        "Nine stone arches",
        "Railway architecture",
        "Train views",
        "Tea-country scenery",
        "Photography",
      ],
    ),
    HeritagePlace(
      id: "gal-vihara-polonnaruwa",
      category: "Temples",
      name: "Gal Vihara Buddha Figures",
      imagePath: "assets/places/gal_vihara_buddha_figures_polonnaruwa.jpg",
      shortDescription: "Celebrated group of Buddha images carved directly into granite at ancient Polonnaruwa.",
      description: "Gal Vihara is renowned for its monumental Buddha figures carved from a single granite outcrop. The seated, standing and reclining images are among the finest surviving works of sculpture from the Polonnaruwa period and form an important part of the ancient city's Buddhist heritage.",
      city: "Polonnaruwa",
      district: "Polonnaruwa",
      address: "Gal Vihara, Ancient City of Polonnaruwa, Sri Lanka",
      historicalPeriod: "Polonnaruwa Kingdom; 12th century CE",
      openingHours:
          "Check current official Polonnaruwa archaeological-site information",
      entranceFee: "Check current official Polonnaruwa ticket information",
      accessibilityInfo: "Outdoor archaeological-site access involves walking. Visitors should follow religious-site etiquette and posted access guidance.",
      latitude: 7.9663,
      longitude: 81.0047,
      rating: 0,
      reviewCount: 0,
      isActive: true,
      isFeatured: false,
      highlights: [
        "Reclining Buddha",
        "Standing Buddha",
        "Seated Buddha images",
        "Granite sculpture",
        "Ancient Buddhist art",
      ],
    ),
    HeritagePlace(
      id: "tooth-temple",
      category: "Temples",
      name: "Temple of the Tooth",
      imagePath: "assets/places/temple_of_the_tooth_kandy.jpg",
      shortDescription: "Sacred Buddhist temple in Kandy associated with the Relic of the Tooth of the Buddha.",
      description: "The Temple of the Sacred Tooth Relic, Sri Dalada Maligawa, is one of Sri Lanka's most important Buddhist sites. Located beside Kandy Lake within the historic royal complex, the temple houses the sacred Tooth Relic and remains an active place of worship and pilgrimage.",
      city: "Kandy",
      district: "Kandy",
      address: "Sri Dalada Veediya, Kandy, Central Province, Sri Lanka",
      historicalPeriod: "Kandyan Kingdom; principal surviving complex largely associated with the 17th–18th centuries",
      openingHours: "Check current temple visitor and worship information before visiting",
      entranceFee: "Visitor admission conditions may vary; check current official information",
      accessibilityInfo: "Visitors must follow temple dress requirements and remove footwear in designated areas. Accessibility varies across the historic complex.",
      latitude: 7.2936,
      longitude: 80.6413,
      rating: 0,
      reviewCount: 0,
      isActive: true,
      isFeatured: true,
      highlights: [
        "Sacred Tooth Relic",
        "Temple architecture",
        "Kandy Lake",
        "Royal Palace complex",
        "Daily worship ceremonies",
        "Buddhist heritage",
      ],
    ),
    HeritagePlace(
      id: "worlds-end-horton-plains",
      category: "Nature",
      name: "World's End",
      imagePath: "assets/places/worlds_end_horton_plains.jpg",
      shortDescription: "Dramatic escarpment viewpoint reached through the highland landscape of Horton Plains.",
      description: "World's End is a famous viewpoint within Horton Plains National Park. The trail crosses montane grassland and cloud-forest landscapes before reaching the dramatic escarpment. Visibility is often best earlier in the day before cloud and mist develop.",
      city: "Horton Plains",
      district: "Nuwara Eliya",
      address: "Horton Plains National Park, Central Highlands, Sri Lanka",
      historicalPeriod: "Natural heritage landscape",
      openingHours: "Check current national-park entry and visitor hours before travelling",
      entranceFee: "Check current official national-park ticket information",
      accessibilityInfo: "The main experience requires a substantial walking trail over natural terrain. Weather can change rapidly and some sections may be difficult for visitors with limited mobility.",
      latitude: 6.7817,
      longitude: 80.7947,
      rating: 0,
      reviewCount: 0,
      isActive: true,
      isFeatured: false,
      highlights: [
        "World's End viewpoint",
        "Horton Plains",
        "Cloud forest",
        "Montane grasslands",
        "Hiking",
        "Highland scenery",
      ],
    ),
    HeritagePlace(
      id: "kandasamy-kovil-trincomalee",
      category: "Temples",
      name: "Kandasamy Kovil",
      imagePath: "assets/places/kandasamy_kovil_trincomalee.jpg",
      shortDescription: "Important Hindu sacred site associated with Trincomalee's historic temple landscape.",
      description: "This Hindu sacred site represents the long-standing Tamil Hindu religious heritage of the Trincomalee region. Visitors should treat the temple as an active place of worship and follow all local dress, photography and religious-etiquette requirements.",
      city: "Trincomalee",
      district: "Trincomalee",
      address: "Trincomalee, Eastern Province, Sri Lanka",
      historicalPeriod: "Historic Hindu religious tradition",
      openingHours: "Temple access varies around worship and festival schedules; check locally before visiting",
      entranceFee: "Check current temple visitor information",
      accessibilityInfo: "This is an active religious site. Follow posted visitor guidance and dress requirements. Accessibility may vary within the temple complex.",
      latitude: 8.5828,
      longitude: 81.2451,
      rating: 0,
      reviewCount: 0,
      isActive: true,
      isFeatured: false,
      highlights: [
        "Hindu religious heritage",
        "Temple architecture",
        "Worship traditions",
        "Trincomalee cultural landscape",
      ],
    ),
    HeritagePlace(
      id: "mulkirigala-rock-temples",
      category: "Temples",
      name: "Mulkirigala Rock Temples",
      imagePath: "assets/places/mulkirigala_rock_temples_tangalle.jpg",
      shortDescription: "Historic Buddhist rock-temple complex built around a dramatic rocky outcrop in southern Sri Lanka.",
      description: "Mulkirigala is an ancient Buddhist temple complex arranged on terraces around a large rock. Cave shrines contain reclining Buddha images, paintings and religious sculpture, while stairways connect the different levels of the site.",
      city: "Mulkirigala",
      district: "Hambantota",
      address: "Mulkirigala Raja Maha Vihara, Southern Province, Sri Lanka",
      historicalPeriod:
          "Ancient Buddhist origins with later-period additions and paintings",
      openingHours: "Check current temple visitor information",
      entranceFee: "Check current visitor information",
      accessibilityInfo: "The site contains numerous stairs and steep sections between temple levels and may be difficult for visitors with limited mobility.",
      latitude: 6.1206,
      longitude: 80.7414,
      rating: 0,
      reviewCount: 0,
      isActive: true,
      isFeatured: false,
      highlights: [
        "Rock temples",
        "Cave shrines",
        "Buddha statues",
        "Murals",
        "Temple terraces",
        "Views from the rock",
      ],
    ),
    HeritagePlace(
      id: "liptons-seat-haputale",
      category: "Nature",
      name: "Lipton's Seat",
      imagePath: "assets/places/liptons_seat_haputale.jpg",
      shortDescription: "Hill-country viewpoint overlooking tea estates and valleys near Haputale.",
      description: "Lipton's Seat is a panoramic viewpoint in Sri Lanka's tea country, associated with the history of the surrounding tea estates. The route passes through plantations and highland scenery before reaching the viewpoint.",
      city: "Haputale",
      district: "Badulla",
      address: "Lipton's Seat, Dambatenne area, Haputale, Sri Lanka",
      historicalPeriod: "Colonial tea-estate heritage",
      openingHours: "Visit during suitable daylight and weather; check current local access conditions",
      entranceFee: "Local access charges may apply; check current information",
      accessibilityInfo: "Road and walking conditions vary. The final approach and viewpoint may present difficulties for visitors with limited mobility.",
      latitude: 6.7803,
      longitude: 81.0158,
      rating: 0,
      reviewCount: 0,
      isActive: true,
      isFeatured: false,
      highlights: [
        "Panoramic viewpoint",
        "Tea estates",
        "Hill-country scenery",
        "Dambatenne area",
        "Photography",
      ],
    ),
    HeritagePlace(
      id: "kiri-vihara-polonnaruwa",
      category: "Temples",
      name: "Kiri Vihara Dagoba",
      imagePath: "assets/places/kiri_vihara_dagoba_polonnaruwa.jpg",
      shortDescription: "Well-preserved white stupa forming part of the ancient religious landscape of Polonnaruwa.",
      description: "Kiri Vihara is a prominent ancient stupa in Polonnaruwa, located close to the Lankatilaka complex. Its surviving form provides an impressive example of Buddhist religious architecture from the medieval capital.",
      city: "Polonnaruwa",
      district: "Polonnaruwa",
      address: "Ancient City of Polonnaruwa, Polonnaruwa, Sri Lanka",
      historicalPeriod: "Polonnaruwa Kingdom; 12th century CE",
      openingHours:
          "Check current official Polonnaruwa archaeological-site information",
      entranceFee: "Check current official Polonnaruwa ticket information",
      accessibilityInfo: "Outdoor archaeological-site access involves walking over historic and sometimes uneven surfaces.",
      latitude: 7.9658,
      longitude: 81.0040,
      rating: 0,
      reviewCount: 0,
      isActive: true,
      isFeatured: false,
      highlights: [
        "Ancient stupa",
        "Buddhist architecture",
        "Polonnaruwa ruins",
        "Religious heritage",
        "Nearby Lankatilaka complex",
      ],
    ),
    HeritagePlace(
      id: "jaffna-fort",
      category: "Forts",
      name: "Jaffna Fort",
      imagePath: "assets/places/jaffna_fort_jaffna.jpg",
      shortDescription: "Large historic coastal fort reflecting Portuguese, Dutch and later colonial influence in northern Sri Lanka.",
      description: "Jaffna Fort is one of the major surviving colonial fortifications in Sri Lanka. Its origins are associated with Portuguese rule, after which the Dutch substantially expanded and reconstructed the fort. The site later passed into British control and remains an important landmark in Jaffna.",
      city: "Jaffna",
      district: "Jaffna",
      address: "Jaffna Fort, Jaffna, Northern Province, Sri Lanka",
      historicalPeriod:
          "Portuguese and Dutch colonial periods, with later British use",
      openingHours: "Check current archaeological-site visitor information",
      entranceFee: "Check current visitor information",
      accessibilityInfo: "Large sections require outdoor walking and some historic surfaces may be uneven.",
      latitude: 9.6621,
      longitude: 80.0089,
      rating: 0,
      reviewCount: 0,
      isActive: true,
      isFeatured: true,
      highlights: [
        "Fort walls",
        "Bastions",
        "Colonial architecture",
        "Jaffna waterfront",
        "Historic ruins",
      ],
    ),
    HeritagePlace(
      id: "mihintale-peak-and-ruins",
      category: "Temples",
      name: "Mihintale Peak and Ruins",
      imagePath: "assets/places/mihintale_peak_and_ruins_anuradhapura.jpg",
      shortDescription: "Ancient Buddhist pilgrimage landscape traditionally associated with the introduction of Buddhism to Sri Lanka.",
      description: "Mihintale is one of Sri Lanka's most significant Buddhist pilgrimage sites. The hill and surrounding archaeological complex contain ancient monastic remains, stupas, stone stairways, caves and viewpoints. Sri Lankan Buddhist tradition associates Mihintale with the meeting of Arahat Mahinda and King Devanampiya Tissa.",
      city: "Mihintale",
      district: "Anuradhapura",
      address: "Mihintale, Anuradhapura District, Sri Lanka",
      historicalPeriod: "Ancient Anuradhapura period; Buddhist tradition from the 3rd century BCE",
      openingHours:
          "Check current temple and archaeological-site visitor information",
      entranceFee: "Check current official visitor information",
      accessibilityInfo: "The site requires significant stair climbing and walking on elevated and uneven terrain.",
      latitude: 8.3500,
      longitude: 80.5167,
      rating: 0,
      reviewCount: 0,
      isActive: true,
      isFeatured: true,
      highlights: [
        "Mihintale hill",
        "Ancient stairway",
        "Stupas",
        "Monastic ruins",
        "Caves",
        "Buddhist pilgrimage heritage",
        "Panoramic views",
      ],
    ),
    HeritagePlace(
      id: "japanese-peace-pagoda-unawatuna",
      category: "Temples",
      name: "Japanese Peace Pagoda",
      imagePath: "assets/places/japanese_peace_pagoda_unawatuna.jpg",
      shortDescription: "White Buddhist peace pagoda overlooking the coastline near Unawatuna and Galle.",
      description: "The Japanese Peace Pagoda near Unawatuna is a modern Buddhist monument set on a hill above the southern coast. Its elevated location provides views towards the ocean and surrounding coastline and offers visitors a quiet religious setting.",
      city: "Unawatuna",
      district: "Galle",
      address: "Rumassala, Unawatuna, Galle District, Sri Lanka",
      historicalPeriod: "Modern Buddhist monument",
      openingHours:
          "Check current local visitor and religious-site information",
      entranceFee: "Check current visitor information",
      accessibilityInfo: "Access involves travelling uphill and conditions may vary. Visitors should respect the site as an active Buddhist religious place.",
      latitude: 6.0188,
      longitude: 80.2386,
      rating: 0,
      reviewCount: 0,
      isActive: true,
      isFeatured: false,
      highlights: [
        "Peace Pagoda",
        "Buddhist monument",
        "Ocean views",
        "Rumassala",
        "Sunset scenery",
        "Quiet religious setting",
      ],
    ),
  ];
}
